{{ application_environment }}:
  adapter: postgresql
  host:     {{ hostvars['localhost']['rds_endpoint'] }}
  database: {{ database_name }}
  username: {{ database_user }}
  password: {{ database_password }}
  pool: 15
