image: "ruby:2.5"
services:
  - postgres:latest
  - elasticsearch:latest
variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
stages:
  - test
before_script:
  - apt-get update -q && apt-get install nodejs -yqq
  - bundle install --without postgres production --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rails db:create db:schema:load
#  - ruby -v
#  - which ruby
#  - cp config/database.yml.gitlab config/database.yml
#  - apt-get update -q && apt-get install nodejs -yqq && apt-get install postgresql -y
#  - apt-get install -y -qq postgresql-contrib libpq-dev cmake
#  - gem install bundler --no-ri --no-rdoc
#  - bundle install -j $(nproc) --path vendor
#  - bundle exec rake db:migrate
#  - bundle exec rake db:test:prepare

test:
  stage: test
  script:
    - bundle exec rspec
    - bundle exec brakeman -z -q
    - bundle exec rubocop

#rspec:
#  script:
#    - bundle exec rspec
#
#brakeman:
#  script:
#    - bundle exec brakeman -z -q
#
#rubocop:
#  script:
#    - bundle exec rubocop
