image: "ruby:2.5"
services:
  - postgres:latest
variables:
  POSTGRES_DB: test_bookaphotos
#  POSTGRES_USER: postgres
#  POSTGRES_PASSWORD: ''
  RAILS_ENV: test
  DATABASE_URL: "postgresql://postgres:postgres@:5432/$POSTGRES_DB"
cache:
  paths:
    - vendor/ruby
before_script:
  - ruby -v
  - which ruby
  - cp config/database.yml.gitlab config/database.yml
  - apt-get update -q && apt-get install nodejs -yqq && apt-get install postgresql -y
  - apt-get install -y -qq postgresql-contrib libpq-dev cmake
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

rspec:
  script:
    - bundle exec rspec

brakeman:
  script:
    - bundle exec brakeman -z -q

rubocop:
  script:
    - bundle exec rubocop
