image: "ruby:2.5.0"
services:
  - postgres:latest
variables:
  POSTGRES_DB: test_bookaphotos
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  RAILS_ENV: test
before_script:
  - ruby -v
  - which ruby
  - apt-get update -q && apt-get install nodejs -yqq && apt-get install postgresql -y
  - apt-get install -y -qq postgresql-contrib libpq-dev cmake
  - gem install bundler --no-ri --no-rdoc
  - bundle install --quiet
  - bundle exec rake db:migrate --quiet
  - bundle exec rake db:test:prepare --quiet

rspec:
  script:
    - bundle exec rspec

brakeman:
  script:
    - bundle exec brakeman -z -q

rubocop:
  script:
    - bundle exec rubocop