image: "ruby:2.5"
services:
  - postgres:latest
  - elasticsearch:latest
variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  LANG: "en_US.UTF-8"
stages:
  - test
  - deploy
before_script:
  - apt-get update -q && apt-get install nodejs -yqq
  - bundle install --without postgres production --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rails db:create db:schema:load

rspec:
  stage: test
  script:
    - bundle exec rspec
brakeman:
  stage: test
  script:
    - bundle exec brakeman -z -q --skip-files app/views/
rubocop:
  stage: test
  script:
    - bundle exec rubocop

deploy_application:
  stage: deploy
  script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
     - eval $(ssh-agent -s)
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - gem install capistrano
    - cap production deploy
  only:
    - master