services:
  - mysql:latest
variables:
  MYSQL_DATABASE: test_bookaphotos
  MYSQL_ROOT_PASSWORD: ""
before_script:
  - ruby -v
  - which ruby
  - apt-get update -q && apt-get install nodejs -yqq && apt-get install mysql-server mysql-client -y
  - gem install bundler --no-ri --no-rdoc
  - bundle install --quiet
  - bundle exec rake db:migrate --quiet
  - bundle exec rake db:test:prepare --quiet

rspec:
  script:
    - rspec

brakeman:
  script:
    - bundle exec brakeman -z -q

rubocop:
  script:
    - bundle exec rubocop