development: &db
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bookaphotos
  pool: 5
  username: <%= ENV.fetch('DB_DEV_USERNAME') { 'root' } %>
    password: <%= ENV.fetch('DB_DEV_PASSWORD') { '' } %>
  host: localhost

test:
  <<: *db
  database: test_bookaphotos

production:
  <<: *db
  database: bookaphotos
